version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: flwbs-nginx
    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.conf:/etc/nginx/sites-available/default
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
    environment:
      - MY_IP_ADDRESS=192.168.26.136

